// ============================================================
// Ivrit Quest — curriculum data
// ============================================================

const LETTERS = [
  { char: 'א', name: 'Alef',   nameHe: 'אָלֶף',   sound: 'Silent — it carries the vowel',        mnemonic: "Alef is a silent ninja — it makes no sound of its own, it just carries vowels!", memoji: '🥷', word: { he: 'אַבָּא', plain: 'אבא', translit: 'AH-ba', en: 'dad', emoji: '👨' } },
  { char: 'ב', name: 'Bet',    nameHe: 'בֵּית',   sound: '"B" as in Ball',                        mnemonic: "Bet looks like a Bayit — a house with an open door. Bet = B for Bayit!", memoji: '🏠', word: { he: 'בַּיִת', plain: 'בית', translit: 'BAH-yit', en: 'house', emoji: '🏠' } },
  { char: 'ג', name: 'Gimel',  nameHe: 'גִימֶל',  sound: '"G" as in Game',                        mnemonic: "Gimel is a Gamal — a camel striding on long legs across the desert!", memoji: '🐫', word: { he: 'גָּמָל', plain: 'גמל', translit: 'ga-MAL', en: 'camel', emoji: '🐫' } },
  { char: 'ד', name: 'Dalet',  nameHe: 'דָלֶת',   sound: '"D" as in Door',                        mnemonic: "Dalet is a Delet — a door! See the doorframe shape? D for Door!", memoji: '🚪', word: { he: 'דָּג', plain: 'דג', translit: 'dag', en: 'fish', emoji: '🐟' } },
  { char: 'ה', name: 'Hey',    nameHe: 'הֵא',     sound: '"H" as in Hello',                       mnemonic: "Hey! It's a window with a gap — lean out and shout 'HEY!' through it!", memoji: '👋', word: { he: 'הַר', plain: 'הר', translit: 'har', en: 'mountain', emoji: '⛰️' } },
  { char: 'ו', name: 'Vav',    nameHe: 'וָו',     sound: '"V" as in Van',                         mnemonic: "Vav is a hook on the wall — one straight line, hang your coat on it!", memoji: '🪝', word: { he: 'וֶרֶד', plain: 'ורד', translit: 'VE-red', en: 'rose', emoji: '🌹' } },
  { char: 'ז', name: 'Zayin',  nameHe: 'זַיִן',   sound: '"Z" as in Zebra',                       mnemonic: "Zayin looks like a sword — swish it through the air: ZZZZ!", memoji: '⚔️', word: { he: 'זֶבְּרָה', plain: 'זברה', translit: 'ZEB-ra', en: 'zebra', emoji: '🦓' } },
  { char: 'ח', name: 'Chet',   nameHe: 'חֵית',    sound: '"CH" from the throat, like "Bach"',     mnemonic: "Chet is a doorway with NO gap. The sound comes from your throat — CHHH!", memoji: '🐸', word: { he: 'חָלָב', plain: 'חלב', translit: 'cha-LAV', en: 'milk', emoji: '🥛' } },
  { char: 'ט', name: 'Tet',    nameHe: 'טֵית',    sound: '"T" as in Top',                         mnemonic: "Tet is a snake curling up inside a basket — sneaky T!", memoji: '🐍', word: { he: 'טֶלֶפוֹן', plain: 'טלפון', translit: 'te-le-FON', en: 'phone', emoji: '📱' } },
  { char: 'י', name: 'Yod',    nameHe: 'יוֹד',    sound: '"Y" as in Yes',                         mnemonic: "Yod is the TINIEST letter — a little apostrophe floating in the air!", memoji: '🐜', word: { he: 'יָד', plain: 'יד', translit: 'yad', en: 'hand', emoji: '✋' } },
  { char: 'כ', name: 'Kaf',    nameHe: 'כַּף',    sound: '"K" as in Kite',                        mnemonic: "Kaf means 'palm' — it's a hand curved to catch a ball. K for Kaf!", memoji: '🤲', word: { he: 'כֶּלֶב', plain: 'כלב', translit: 'KE-lev', en: 'dog', emoji: '🐶' } },
  { char: 'ל', name: 'Lamed',  nameHe: 'לָמֶד',   sound: '"L" as in Lion',                        mnemonic: "Lamed is the TALLEST letter — a lighthouse towering over the alphabet!", memoji: '🗼', word: { he: 'לֵב', plain: 'לב', translit: 'lev', en: 'heart', emoji: '❤️' } },
  { char: 'מ', name: 'Mem',    nameHe: 'מֵם',     sound: '"M" as in Moon',                        mnemonic: "Mem is a wave in the sea — Mayim means water! M for Mayim!", memoji: '🌊', word: { he: 'מַיִם', plain: 'מים', translit: 'MA-yim', en: 'water', emoji: '💧' } },
  { char: 'נ', name: 'Nun',    nameHe: 'נוּן',    sound: '"N" as in Night',                       mnemonic: "Nun is a little candle flame bending in the breeze!", memoji: '🕯️', word: { he: 'נֵר', plain: 'נר', translit: 'ner', en: 'candle', emoji: '🕯️' } },
  { char: 'ס', name: 'Samech', nameHe: 'סָמֶך',   sound: '"S" as in Sun',                         mnemonic: "Samech is a full circle — like a donut. S for Sufganiya (donut)!", memoji: '🍩', word: { he: 'סֵפֶר', plain: 'ספר', translit: 'SE-fer', en: 'book', emoji: '📖' } },
  { char: 'ע', name: 'Ayin',   nameHe: 'עַיִן',   sound: 'Silent — a deep quiet letter',          mnemonic: "Ayin means 'eye' — it watches everything but says nothing!", memoji: '👁️', word: { he: 'עֵץ', plain: 'עץ', translit: 'ets', en: 'tree', emoji: '🌳' } },
  { char: 'פ', name: 'Pey',    nameHe: 'פֵּא',    sound: '"P" as in Pizza',                       mnemonic: "Pey means 'mouth' — look, there's a little mouth hiding inside the letter!", memoji: '👄', word: { he: 'פִּיל', plain: 'פיל', translit: 'peel', en: 'elephant', emoji: '🐘' } },
  { char: 'צ', name: 'Tsadi',  nameHe: 'צַדִי',   sound: '"TS" as in piTSa',                      mnemonic: "Tsadi says TS — like the middle of 'pizza'! piTSa!", memoji: '🍕', word: { he: 'צָב', plain: 'צב', translit: 'tsav', en: 'turtle', emoji: '🐢' } },
  { char: 'ק', name: 'Kof',    nameHe: 'קוֹף',    sound: '"K" as in King',                        mnemonic: "Kof means 'monkey' — see its long tail hanging down below the line?", memoji: '🐒', word: { he: 'קוֹף', plain: 'קוף', translit: 'kof', en: 'monkey', emoji: '🐒' } },
  { char: 'ר', name: 'Resh',   nameHe: 'רֵישׁ',   sound: '"R" as in Run',                         mnemonic: "Resh is a head looking left — Rosh means head! R for Rosh!", memoji: '🙂', word: { he: 'רַכֶּבֶת', plain: 'רכבת', translit: 'ra-KE-vet', en: 'train', emoji: '🚂' } },
  { char: 'ש', name: 'Shin',   nameHe: 'שִׁין',   sound: '"SH" as in Shhh!',                      mnemonic: "Shin has three flames rising up — fire! SHHH, don't wake the dragon!", memoji: '🔥', word: { he: 'שֶׁמֶשׁ', plain: 'שמש', translit: 'SHE-mesh', en: 'sun', emoji: '☀️' } },
  { char: 'ת', name: 'Tav',    nameHe: 'תָו',     sound: '"T" as in Taco',                        mnemonic: "Tav is a dancer with one foot kicked out — Ta-da! T for Ta-da!", memoji: '💃', word: { he: 'תַּפּוּחַ', plain: 'תפוח', translit: 'ta-PU-ach', en: 'apple', emoji: '🍎' } },
];

// Final (sofit) forms — letters that change shape at the END of a word
const FINALS = [
  { char: 'ך', name: 'Final Chaf',  nameHe: 'כַף סוֹפִית',  sound: 'Same as כ — at the end of a word', mnemonic: "When Kaf comes LAST in a word it stretches its leg down: ך. Same sound, long legs!", memoji: '🦵', word: { he: 'מֶלֶךְ', plain: 'מלך', translit: 'ME-lech', en: 'king', emoji: '🤴' } },
  { char: 'ם', name: 'Final Mem',   nameHe: 'מֵם סוֹפִית',  sound: 'Same as מ — at the end of a word', mnemonic: "At the end of a word, Mem closes up into a box: ם. Shalom ends with one!", memoji: '📦', word: { he: 'שָׁלוֹם', plain: 'שלום', translit: 'sha-LOM', en: 'hello / peace', emoji: '✌️' } },
  { char: 'ן', name: 'Final Nun',   nameHe: 'נוּן סוֹפִית', sound: 'Same as נ — at the end of a word', mnemonic: "Final Nun stands up straight and slides below the line: ן. A tall candle!", memoji: '🕯️', word: { he: 'בֵּן', plain: 'בן', translit: 'ben', en: 'son / boy', emoji: '👦' } },
  { char: 'ף', name: 'Final Pey',   nameHe: 'פֵּא סוֹפִית', sound: 'Same as פ — at the end of a word', mnemonic: "Final Pey lets its tail hang down: ף. Kof (monkey) ends with one!", memoji: '🐒', word: { he: 'עוֹף', plain: 'עוף', translit: 'of', en: 'chicken', emoji: '🐔' } },
  { char: 'ץ', name: 'Final Tsadi', nameHe: 'צַדִי סוֹפִית', sound: 'Same as צ — at the end of a word', mnemonic: "Final Tsadi stretches down: ץ. Ets (tree) ends with one — roots going down!", memoji: '🌳', word: { he: 'עֵץ', plain: 'עץ', translit: 'ets', en: 'tree', emoji: '🌳' } },
];

// Vowels (nikud) — shown on the letter Bet
const VOWELS = [
  { char: 'בַ',  name: 'Patach',  nameHe: 'פַּתָח',  sound: '"AH" as in father',  mnemonic: "Patach is a flat line UNDER the letter — open wide and say AHHH!", memoji: '😮', word: { he: 'אַבָּא', plain: 'אבא', translit: 'AH-ba', en: 'dad', emoji: '👨' } },
  { char: 'בָ',  name: 'Kamatz',  nameHe: 'קָמָץ',   sound: '"AH" as in father',  mnemonic: "Kamatz is a tiny T under the letter — it ALSO says AH. Two vowels, one sound!", memoji: '👨‍🦱', word: { he: 'שָׁלוֹם', plain: 'שלום', translit: 'sha-LOM', en: 'hello', emoji: '✌️' } },
  { char: 'בִ',  name: 'Chirik',  nameHe: 'חִירִיק', sound: '"EE" as in bee',     mnemonic: "Chirik is one tiny dot — tiny dot, tiny sound: EEEE!", memoji: '🐝', word: { he: 'פִּיל', plain: 'פיל', translit: 'peel', en: 'elephant', emoji: '🐘' } },
  { char: 'בֶ',  name: 'Segol',   nameHe: 'סֶגוֹל',  sound: '"EH" as in egg',     mnemonic: "Segol is three dots in a triangle — three eggs in a nest saying EH!", memoji: '🥚', word: { he: 'דֶגֶל', plain: 'דגל', translit: 'DE-gel', en: 'flag', emoji: '🇮🇱' } },
  { char: 'בוֹ', name: 'Cholam',  nameHe: 'חוֹלָם',  sound: '"OH" as in go',      mnemonic: "Cholam is a dot floating ON TOP — a balloon going OH so high!", memoji: '🎈', word: { he: 'בּוֹקֶר', plain: 'בוקר', translit: 'BO-ker', en: 'morning', emoji: '🌅' } },
  { char: 'בוּ', name: 'Shuruk',  nameHe: 'שׁוּרוּק', sound: '"OO" as in moon',    mnemonic: "Shuruk is a Vav with a dot in its middle — a rocket saying OOOO to the moon!", memoji: '🚀', word: { he: 'תַּפּוּחַ', plain: 'תפוח', translit: 'ta-PU-ach', en: 'apple', emoji: '🍎' } },
];

// Vocabulary sets — { he (with nikud), plain (no nikud, for TTS + speech matching), translit, en, emoji }
const VOCAB = {
  greetings: [
    { he: 'שָׁלוֹם', plain: 'שלום', translit: 'sha-LOM', en: 'hello / peace', emoji: '✌️' },
    { he: 'בּוֹקֶר טוֹב', plain: 'בוקר טוב', translit: 'BO-ker tov', en: 'good morning', emoji: '🌅' },
    { he: 'לַיְלָה טוֹב', plain: 'לילה טוב', translit: 'LY-la tov', en: 'good night', emoji: '🌙' },
    { he: 'תּוֹדָה', plain: 'תודה', translit: 'to-DA', en: 'thank you', emoji: '🙏' },
    { he: 'בְּבַקָּשָׁה', plain: 'בבקשה', translit: 'be-va-ka-SHA', en: 'please', emoji: '🤝' },
    { he: 'כֵּן', plain: 'כן', translit: 'ken', en: 'yes', emoji: '✅' },
    { he: 'לֹא', plain: 'לא', translit: 'lo', en: 'no', emoji: '❌' },
    { he: 'סְלִיחָה', plain: 'סליחה', translit: 'sli-CHA', en: 'sorry / excuse me', emoji: '😅' },
    { he: 'מַה נִשְׁמָע?', plain: 'מה נשמע', translit: 'ma nish-MA', en: "what's up?", emoji: '🤙' },
    { he: 'לְהִתְרָאוֹת', plain: 'להתראות', translit: 'le-hit-ra-OT', en: 'see you later', emoji: '👋' },
  ],
  family: [
    { he: 'אַבָּא', plain: 'אבא', translit: 'AH-ba', en: 'dad', emoji: '👨' },
    { he: 'אִמָא', plain: 'אמא', translit: 'EE-ma', en: 'mom', emoji: '👩' },
    { he: 'אָח', plain: 'אח', translit: 'ach', en: 'brother', emoji: '👦' },
    { he: 'אָחוֹת', plain: 'אחות', translit: 'a-CHOT', en: 'sister', emoji: '👧' },
    { he: 'סַבָּא', plain: 'סבא', translit: 'SA-ba', en: 'grandpa', emoji: '👴' },
    { he: 'סַבְתָא', plain: 'סבתא', translit: 'SAV-ta', en: 'grandma', emoji: '👵' },
    { he: 'מִשְׁפָּחָה', plain: 'משפחה', translit: 'mish-pa-CHA', en: 'family', emoji: '👨‍👩‍👧‍👦' },
    { he: 'חָבֵר', plain: 'חבר', translit: 'cha-VER', en: 'friend', emoji: '🧑‍🤝‍🧑' },
  ],
  numbers: [
    { he: 'אַחַת', plain: 'אחת', translit: 'a-CHAT', en: 'one', emoji: '1️⃣' },
    { he: 'שְׁתַּיִם', plain: 'שתיים', translit: 'SHTA-yim', en: 'two', emoji: '2️⃣' },
    { he: 'שָׁלוֹשׁ', plain: 'שלוש', translit: 'sha-LOSH', en: 'three', emoji: '3️⃣' },
    { he: 'אַרְבַּע', plain: 'ארבע', translit: 'AR-ba', en: 'four', emoji: '4️⃣' },
    { he: 'חָמֵשׁ', plain: 'חמש', translit: 'cha-MESH', en: 'five', emoji: '5️⃣' },
    { he: 'שֵׁשׁ', plain: 'שש', translit: 'shesh', en: 'six', emoji: '6️⃣' },
    { he: 'שֶׁבַע', plain: 'שבע', translit: 'SHE-va', en: 'seven', emoji: '7️⃣' },
    { he: 'שְׁמוֹנֶה', plain: 'שמונה', translit: 'shmo-NE', en: 'eight', emoji: '8️⃣' },
    { he: 'תֵּשַׁע', plain: 'תשע', translit: 'TE-sha', en: 'nine', emoji: '9️⃣' },
    { he: 'עֶשֶׂר', plain: 'עשר', translit: 'E-ser', en: 'ten', emoji: '🔟' },
  ],
  colors: [
    { he: 'אָדוֹם', plain: 'אדום', translit: 'a-DOM', en: 'red', emoji: '🔴' },
    { he: 'כָּחוֹל', plain: 'כחול', translit: 'ka-CHOL', en: 'blue', emoji: '🔵' },
    { he: 'יָרוֹק', plain: 'ירוק', translit: 'ya-ROK', en: 'green', emoji: '🟢' },
    { he: 'צָהוֹב', plain: 'צהוב', translit: 'tsa-HOV', en: 'yellow', emoji: '🟡' },
    { he: 'כָּתוֹם', plain: 'כתום', translit: 'ka-TOM', en: 'orange', emoji: '🟠' },
    { he: 'סָגוֹל', plain: 'סגול', translit: 'sa-GOL', en: 'purple', emoji: '🟣' },
    { he: 'וָרוֹד', plain: 'ורוד', translit: 'va-ROD', en: 'pink', emoji: '🌸' },
    { he: 'שָׁחוֹר', plain: 'שחור', translit: 'sha-CHOR', en: 'black', emoji: '⚫' },
    { he: 'לָבָן', plain: 'לבן', translit: 'la-VAN', en: 'white', emoji: '⚪' },
  ],
  animals: [
    { he: 'כֶּלֶב', plain: 'כלב', translit: 'KE-lev', en: 'dog', emoji: '🐶' },
    { he: 'חָתוּל', plain: 'חתול', translit: 'cha-TUL', en: 'cat', emoji: '🐱' },
    { he: 'סוּס', plain: 'סוס', translit: 'sus', en: 'horse', emoji: '🐴' },
    { he: 'דָּג', plain: 'דג', translit: 'dag', en: 'fish', emoji: '🐟' },
    { he: 'צִפּוֹר', plain: 'ציפור', translit: 'tsi-POR', en: 'bird', emoji: '🐦' },
    { he: 'פִּיל', plain: 'פיל', translit: 'peel', en: 'elephant', emoji: '🐘' },
    { he: 'אַרְיֵה', plain: 'אריה', translit: 'ar-YE', en: 'lion', emoji: '🦁' },
    { he: 'קוֹף', plain: 'קוף', translit: 'kof', en: 'monkey', emoji: '🐒' },
    { he: 'פָּרָה', plain: 'פרה', translit: 'pa-RA', en: 'cow', emoji: '🐮' },
    { he: 'צָב', plain: 'צב', translit: 'tsav', en: 'turtle', emoji: '🐢' },
  ],
  science: [
    { he: 'מַדָּע', plain: 'מדע', translit: 'ma-DA', en: 'science', emoji: '🔬' },
    { he: 'מַדְעָן', plain: 'מדען', translit: 'mad-AN', en: 'scientist', emoji: '👩‍🔬' },
    { he: 'נִסּוּי', plain: 'ניסוי', translit: 'ni-SUY', en: 'experiment', emoji: '🧪' },
    { he: 'מַעְבָּדָה', plain: 'מעבדה', translit: 'ma-ba-DA', en: 'laboratory', emoji: '🥼' },
    { he: 'מִיקְרוֹסְקוֹפ', plain: 'מיקרוסקופ', translit: 'mik-ro-SKOP', en: 'microscope', emoji: '🔬' },
    { he: 'דִּינוֹזָאוּר', plain: 'דינוזאור', translit: 'di-no-ZA-ur', en: 'dinosaur', emoji: '🦖' },
    { he: 'מוֹחַ', plain: 'מוח', translit: 'MO-ach', en: 'brain', emoji: '🧠' },
    { he: 'חַשְׁמַל', plain: 'חשמל', translit: 'chash-MAL', en: 'electricity', emoji: '⚡' },
    { he: 'מַגְנֵט', plain: 'מגנט', translit: 'mag-NET', en: 'magnet', emoji: '🧲' },
    { he: 'רוֹבּוֹט', plain: 'רובוט', translit: 'RO-bot', en: 'robot', emoji: '🤖' },
  ],
  space: [
    { he: 'חָלָל', plain: 'חלל', translit: 'cha-LAL', en: 'space', emoji: '🌌' },
    { he: 'כּוֹכָב', plain: 'כוכב', translit: 'ko-CHAV', en: 'star', emoji: '⭐' },
    { he: 'כּוֹכָב לֶכֶת', plain: 'כוכב לכת', translit: 'ko-CHAV LE-chet', en: 'planet', emoji: '🪐' },
    { he: 'יָרֵחַ', plain: 'ירח', translit: 'ya-RE-ach', en: 'moon', emoji: '🌙' },
    { he: 'שֶׁמֶשׁ', plain: 'שמש', translit: 'SHE-mesh', en: 'sun', emoji: '☀️' },
    { he: 'כַּדּוּר הָאָרֶץ', plain: 'כדור הארץ', translit: 'ka-DUR ha-A-rets', en: 'Earth', emoji: '🌍' },
    { he: 'אַסְטְרוֹנָאוּט', plain: 'אסטרונאוט', translit: 'as-tro-NA-ut', en: 'astronaut', emoji: '👨‍🚀' },
    { he: 'חֲלָלִית', plain: 'חללית', translit: 'cha-la-LIT', en: 'spaceship', emoji: '🛸' },
    { he: 'טִיל', plain: 'טיל', translit: 'til', en: 'rocket', emoji: '🚀' },
    { he: 'חַיְזָר', plain: 'חיזר', translit: 'chai-ZAR', en: 'alien', emoji: '👽' },
  ],
  food: [
    { he: 'לֶחֶם', plain: 'לחם', translit: 'LE-chem', en: 'bread', emoji: '🍞' },
    { he: 'מַיִם', plain: 'מים', translit: 'MA-yim', en: 'water', emoji: '💧' },
    { he: 'תַּפּוּחַ', plain: 'תפוח', translit: 'ta-PU-ach', en: 'apple', emoji: '🍎' },
    { he: 'בָּנָנָה', plain: 'בננה', translit: 'ba-NA-na', en: 'banana', emoji: '🍌' },
    { he: 'גְּלִידָה', plain: 'גלידה', translit: 'GLEE-da', en: 'ice cream', emoji: '🍦' },
    { he: 'פִּיצָה', plain: 'פיצה', translit: 'PEE-tsa', en: 'pizza', emoji: '🍕' },
    { he: 'חָלָב', plain: 'חלב', translit: 'cha-LAV', en: 'milk', emoji: '🥛' },
    { he: 'עוּגָה', plain: 'עוגה', translit: 'u-GA', en: 'cake', emoji: '🍰' },
    { he: 'שׁוֹקוֹלָד', plain: 'שוקולד', translit: 'sho-ko-LAD', en: 'chocolate', emoji: '🍫' },
    { he: 'פָלָאפֶל', plain: 'פלאפל', translit: 'fa-LA-fel', en: 'falafel', emoji: '🧆' },
  ],
};

// Sentences — words[] are the plain-Hebrew tiles for the "build it" game
const SENTENCES_1 = [
  { he: 'אֲנִי רוֹצֶה פִּיצָה', plain: 'אני רוצה פיצה', words: ['אני', 'רוצה', 'פיצה'], translit: 'a-NEE ro-TSE PEE-tsa', en: 'I want pizza', emoji: '🍕' },
  { he: 'זֶה כֶּלֶב', plain: 'זה כלב', words: ['זה', 'כלב'], translit: 'ze KE-lev', en: 'This is a dog', emoji: '🐶' },
  { he: 'אֲנִי אוֹהֵב גְּלִידָה', plain: 'אני אוהב גלידה', words: ['אני', 'אוהב', 'גלידה'], translit: 'a-NEE o-HEV GLEE-da', en: 'I love ice cream', emoji: '🍦' },
  { he: 'יֵשׁ לִי חָבֵר', plain: 'יש לי חבר', words: ['יש', 'לי', 'חבר'], translit: 'yesh li cha-VER', en: 'I have a friend', emoji: '🧑‍🤝‍🧑' },
  { he: 'אִמָא בַּבַּיִת', plain: 'אמא בבית', words: ['אמא', 'בבית'], translit: 'EE-ma ba-BA-yit', en: 'Mom is at home', emoji: '🏠' },
  { he: 'הַכֶּלֶב גָּדוֹל', plain: 'הכלב גדול', words: ['הכלב', 'גדול'], translit: 'ha-KE-lev ga-DOL', en: 'The dog is big', emoji: '🐕' },
];

const SENTENCES_2 = [
  { he: 'מַה זֶה?', plain: 'מה זה', words: ['מה', 'זה'], translit: 'ma ze?', en: 'What is this?', emoji: '❓' },
  { he: 'אֵיפֹה הֶחָתוּל?', plain: 'איפה החתול', words: ['איפה', 'החתול'], translit: 'EY-fo he-cha-TUL?', en: 'Where is the cat?', emoji: '🐱' },
  { he: 'אֲנִי רָעֵב', plain: 'אני רעב', words: ['אני', 'רעב'], translit: 'a-NEE ra-EV', en: 'I am hungry', emoji: '😋' },
  { he: 'בּוֹקֶר טוֹב אַבָּא', plain: 'בוקר טוב אבא', words: ['בוקר', 'טוב', 'אבא'], translit: 'BO-ker tov AH-ba', en: 'Good morning, Dad', emoji: '🌅' },
  { he: 'אֲנִי רוֹצֶה מַיִם בְּבַקָּשָׁה', plain: 'אני רוצה מים בבקשה', words: ['אני', 'רוצה', 'מים', 'בבקשה'], translit: 'a-NEE ro-TSE MA-yim be-va-ka-SHA', en: 'I want water, please', emoji: '💧' },
  { he: 'אֲנִי מְדַבֵּר עִבְרִית!', plain: 'אני מדבר עברית', words: ['אני', 'מדבר', 'עברית'], translit: 'a-NEE me-da-BER eev-REET!', en: 'I speak Hebrew!', emoji: '🎉' },
];

// --- more vocabulary worlds ---
VOCAB.everyday = [
  { he: 'אֹכֶל', plain: 'אוכל', translit: 'O-chel', en: 'food', emoji: '🍽️' },
  { he: 'מִטָּה', plain: 'מיטה', translit: 'mi-TA', en: 'bed', emoji: '🛏️' },
  { he: 'שֻׁלְחָן', plain: 'שולחן', translit: 'shul-CHAN', en: 'table', emoji: '🪵' },
  { he: 'כִּסֵּא', plain: 'כיסא', translit: 'ki-SE', en: 'chair', emoji: '🪑' },
  { he: 'דֶּלֶת', plain: 'דלת', translit: 'DE-let', en: 'door', emoji: '🚪' },
  { he: 'חַלּוֹן', plain: 'חלון', translit: 'cha-LON', en: 'window', emoji: '🪟' },
  { he: 'מַפְתֵּחַ', plain: 'מפתח', translit: 'maf-TE-ach', en: 'key', emoji: '🔑' },
  { he: 'כֶּסֶף', plain: 'כסף', translit: 'KE-sef', en: 'money', emoji: '💰' },
  { he: 'תִּיק', plain: 'תיק', translit: 'teek', en: 'bag / backpack', emoji: '🎒' },
  { he: 'שָׁעוֹן', plain: 'שעון', translit: 'sha-ON', en: 'clock / watch', emoji: '⏰' },
  { he: 'שֵׁרוּתִים', plain: 'שירותים', translit: 'she-ru-TIM', en: 'bathroom', emoji: '🚽' },
];
VOCAB.transport = [
  { he: 'מְכוֹנִית', plain: 'מכונית', translit: 'me-cho-NIT', en: 'car', emoji: '🚗' },
  { he: 'אוֹטוֹבּוּס', plain: 'אוטובוס', translit: 'O-to-bus', en: 'bus', emoji: '🚌' },
  { he: 'רַכֶּבֶת', plain: 'רכבת', translit: 'ra-KE-vet', en: 'train', emoji: '🚂' },
  { he: 'אוֹפַנַּיִם', plain: 'אופניים', translit: 'o-fa-NA-yim', en: 'bicycle', emoji: '🚲' },
  { he: 'מָטוֹס', plain: 'מטוס', translit: 'ma-TOS', en: 'airplane', emoji: '✈️' },
  { he: 'סִירָה', plain: 'סירה', translit: 'si-RA', en: 'boat', emoji: '⛵' },
  { he: 'רְחוֹב', plain: 'רחוב', translit: 're-CHOV', en: 'street', emoji: '🛣️' },
  { he: 'יָמִינָה', plain: 'ימינה', translit: 'ya-MI-na', en: 'to the right', emoji: '➡️' },
  { he: 'שְׂמֹאלָה', plain: 'שמאלה', translit: 'SMO-la', en: 'to the left', emoji: '⬅️' },
  { he: 'עֲצֹר', plain: 'עצור', translit: 'a-TSOR', en: 'stop!', emoji: '🛑' },
];
VOCAB.games = [
  { he: 'כַּדּוּר', plain: 'כדור', translit: 'ka-DUR', en: 'ball', emoji: '⚽' },
  { he: 'מַגְלֵשָׁה', plain: 'מגלשה', translit: 'mag-le-SHA', en: 'slide', emoji: '🛝' },
  { he: 'נַדְנֵדָה', plain: 'נדנדה', translit: 'nad-ne-DA', en: 'swing', emoji: '🎢' },
  { he: 'קְלָפִים', plain: 'קלפים', translit: 'kla-FIM', en: 'cards', emoji: '🃏' },
  { he: 'שַׁחְמָט', plain: 'שחמט', translit: 'shach-MAT', en: 'chess', emoji: '♟️' },
  { he: 'מִשְׂחָק', plain: 'משחק', translit: 'mis-CHAK', en: 'game', emoji: '🎮' },
  { he: 'צַעֲצוּעַ', plain: 'צעצוע', translit: 'tsa-a-TSU-a', en: 'toy', emoji: '🧸' },
  { he: 'בֻּבָּה', plain: 'בובה', translit: 'bu-BA', en: 'doll', emoji: '🪆' },
  { he: 'פָּאזֶל', plain: 'פאזל', translit: 'PA-zel', en: 'puzzle', emoji: '🧩' },
  { he: 'מַחְבּוֹאִים', plain: 'מחבואים', translit: 'mach-bo-IM', en: 'hide-and-seek', emoji: '🙈' },
];
VOCAB.motion = [
  { he: 'הוֹלֵךְ', plain: 'הולך', translit: 'ho-LECH', en: 'walk', emoji: '🚶' },
  { he: 'רָץ', plain: 'רץ', translit: 'rats', en: 'run', emoji: '🏃' },
  { he: 'קוֹפֵץ', plain: 'קופץ', translit: 'ko-FETS', en: 'jump', emoji: '🦘' },
  { he: 'שׂוֹחֶה', plain: 'שוחה', translit: 'so-CHE', en: 'swim', emoji: '🏊' },
  { he: 'רוֹקֵד', plain: 'רוקד', translit: 'ro-KED', en: 'dance', emoji: '🕺' },
  { he: 'יוֹשֵׁב', plain: 'יושב', translit: 'yo-SHEV', en: 'sit', emoji: '🧘' },
  { he: 'עוֹמֵד', plain: 'עומד', translit: 'o-MED', en: 'stand', emoji: '🧍' },
  { he: 'יָשֵׁן', plain: 'ישן', translit: 'ya-SHEN', en: 'sleep', emoji: '😴' },
  { he: 'אוֹכֵל', plain: 'אוכל', translit: 'o-CHEL', en: 'eat', emoji: '😋' },
  { he: 'מְטַפֵּס', plain: 'מטפס', translit: 'me-ta-PES', en: 'climb', emoji: '🧗' },
];
// Masculine / feminine pairs — `accept` lists forms that count as a correct spoken answer
VOCAB.gender = [
  { he: 'אַתָּה / אַתְּ', plain: 'אתה, את', accept: ['אתה', 'את'], translit: 'a-TA 👦 / at 👧', en: 'you', emoji: '👉' },
  { he: 'הוּא / הִיא', plain: 'הוא, היא', accept: ['הוא', 'היא'], translit: 'hu 👦 / hee 👧', en: 'he / she', emoji: '👦👧' },
  { he: 'יֶלֶד / יַלְדָּה', plain: 'ילד, ילדה', accept: ['ילד', 'ילדה'], translit: 'YE-led 👦 / yal-DA 👧', en: 'boy / girl', emoji: '🧒' },
  { he: 'מוֹרֶה / מוֹרָה', plain: 'מורה, מורה', accept: ['מורה'], translit: 'mo-RE 👦 / mo-RA 👧', en: 'teacher', emoji: '🧑‍🏫' },
  { he: 'הוֹלֵךְ / הוֹלֶכֶת', plain: 'הולך, הולכת', accept: ['הולך', 'הולכת'], translit: 'ho-LECH 👦 / ho-LE-chet 👧', en: 'walks', emoji: '🚶' },
  { he: 'רוֹצֶה / רוֹצָה', plain: 'רוצה, רוצה', accept: ['רוצה'], translit: 'ro-TSE 👦 / ro-TSA 👧', en: 'wants', emoji: '🙏' },
  { he: 'אוֹכֵל / אוֹכֶלֶת', plain: 'אוכל, אוכלת', accept: ['אוכל', 'אוכלת'], translit: 'o-CHEL 👦 / o-CHE-let 👧', en: 'eats', emoji: '😋' },
  { he: 'מְדַבֵּר / מְדַבֶּרֶת', plain: 'מדבר, מדברת', accept: ['מדבר', 'מדברת'], translit: 'me-da-BER 👦 / me-da-BE-ret 👧', en: 'speaks', emoji: '🗣️' },
  { he: 'גָּדוֹל / גְּדוֹלָה', plain: 'גדול, גדולה', accept: ['גדול', 'גדולה'], translit: 'ga-DOL 👦 / gdo-LA 👧', en: 'big', emoji: '🐘' },
  { he: 'קָטָן / קְטַנָּה', plain: 'קטן, קטנה', accept: ['קטן', 'קטנה'], translit: 'ka-TAN 👦 / kta-NA 👧', en: 'small', emoji: '🐜' },
];
// Plurals — masculine -im, feminine -ot (plus the famous irregular bayit → batim)
VOCAB.plural = [
  { he: 'יְלָדִים', plain: 'ילדים', translit: 'ye-la-DIM (one: YE-led)', en: 'kids / boys', emoji: '👦👦' },
  { he: 'יְלָדוֹת', plain: 'ילדות', translit: 'ye-la-DOT (one: yal-DA)', en: 'girls', emoji: '👧👧' },
  { he: 'כְּלָבִים', plain: 'כלבים', translit: 'kla-VIM (one: KE-lev)', en: 'dogs', emoji: '🐶🐶' },
  { he: 'חֲתוּלִים', plain: 'חתולים', translit: 'cha-tu-LIM (one: cha-TUL)', en: 'cats', emoji: '🐱🐱' },
  { he: 'סְפָרִים', plain: 'ספרים', translit: 'sfa-RIM (one: SE-fer)', en: 'books', emoji: '📚' },
  { he: 'כּוֹכָבִים', plain: 'כוכבים', translit: 'ko-cha-VIM (one: ko-CHAV)', en: 'stars', emoji: '✨' },
  { he: 'בָּתִּים', plain: 'בתים', translit: 'ba-TIM (one: BA-yit!)', en: 'houses', emoji: '🏘️' },
  { he: 'בֻּבּוֹת', plain: 'בובות', translit: 'bu-BOT (one: bu-BA)', en: 'dolls', emoji: '🪆🪆' },
  { he: 'עוּגוֹת', plain: 'עוגות', translit: 'u-GOT (one: u-GA)', en: 'cakes', emoji: '🍰🍰' },
  { he: 'מְכוֹנִיּוֹת', plain: 'מכוניות', translit: 'me-cho-ni-YOT (one: me-cho-NIT)', en: 'cars', emoji: '🚗🚗' },
];

// Friendly Hebrew — introduce-yourself conversation (standard masculine forms)
const SENTENCES_FRIENDLY = [
  { he: 'מַה קוֹרְאִים לְךָ?', plain: 'מה קוראים לך', words: ['מה', 'קוראים', 'לך'], translit: 'ma kor-IM le-CHA?', en: "What's your name?", emoji: '🙋' },
  { he: 'קוֹרְאִים לִי דָּנִי', plain: 'קוראים לי דני', words: ['קוראים', 'לי', 'דני'], translit: 'kor-IM li DA-ni', en: 'My name is Dani', emoji: '😊' },
  { he: 'בֶּן כַּמָּה אַתָּה?', plain: 'בן כמה אתה', words: ['בן', 'כמה', 'אתה'], translit: 'ben KA-ma a-TA?', en: 'How old are you?', emoji: '🎂' },
  { he: 'אֲנִי בֶּן עֶשֶׂר', plain: 'אני בן עשר', words: ['אני', 'בן', 'עשר'], translit: 'a-NEE ben E-ser', en: 'I am ten years old', emoji: '🔟' },
  { he: 'אֵיפֹה אַתָּה גָּר?', plain: 'איפה אתה גר', words: ['איפה', 'אתה', 'גר'], translit: 'EY-fo a-TA gar?', en: 'Where do you live?', emoji: '🏠' },
  { he: 'אֲנִי הוֹלֵךְ לְבֵית סֵפֶר', plain: 'אני הולך לבית ספר', words: ['אני', 'הולך', 'לבית', 'ספר'], translit: 'a-NEE ho-LECH le-VEIT SE-fer', en: 'I go to school', emoji: '🎒' },
  { he: 'רוֹצֶה לְשַׂחֵק?', plain: 'רוצה לשחק', words: ['רוצה', 'לשחק'], translit: 'ro-TSE le-sa-CHEK?', en: 'Want to play?', emoji: '⚽' },
  { he: 'אֲנַחְנוּ חֲבֵרִים', plain: 'אנחנו חברים', words: ['אנחנו', 'חברים'], translit: 'a-NACH-nu cha-ve-RIM', en: 'We are friends', emoji: '🤝' },
];

// --- real-life conversation sentences (5 levels × 10) ---
const SENTENCES_LIFE = [
  { he: 'מַה הַשָּׁעָה?', plain: 'מה השעה', words: ['מה', 'השעה'], translit: 'ma ha-sha-A?', en: 'What time is it?', emoji: '🕐' },
  { he: 'אֲנִי צָמֵא, אֲנִי רוֹצֶה מַיִם', plain: 'אני צמא אני רוצה מים', words: ['אני', 'צמא', 'אני', 'רוצה', 'מים'], translit: 'a-NEE tsa-ME, a-NEE ro-TSE MA-yim', en: 'I am thirsty, I want water', emoji: '🥤' },
  { he: 'אֲנִי עָיֵיף, אֲנִי הוֹלֵךְ לִישׁוֹן', plain: 'אני עייף אני הולך לישון', words: ['אני', 'עייף', 'אני', 'הולך', 'לישון'], translit: 'a-NEE a-YEF, a-NEE ho-LECH lee-SHON', en: 'I am tired, I am going to sleep', emoji: '😴' },
  { he: 'בּוֹא הֵנָּה!', plain: 'בוא הנה', words: ['בוא', 'הנה'], translit: 'bo HE-na!', en: 'Come here!', emoji: '👋' },
  { he: 'רַק רֶגַע, בְּבַקָּשָׁה', plain: 'רק רגע בבקשה', words: ['רק', 'רגע', 'בבקשה'], translit: 'rak RE-ga, be-va-ka-SHA', en: 'Just a moment, please', emoji: '⏳' },
  { he: 'אֲנִי לֹא יוֹדֵעַ', plain: 'אני לא יודע', words: ['אני', 'לא', 'יודע'], translit: 'a-NEE lo yo-DE-a', en: "I don't know", emoji: '🤷' },
  { he: 'מַה עוֹשִׂים הַיּוֹם?', plain: 'מה עושים היום', words: ['מה', 'עושים', 'היום'], translit: 'ma o-SIM ha-YOM?', en: 'What are we doing today?', emoji: '📅' },
  { he: 'אֲנִי הוֹלֵךְ הַבַּיְתָה', plain: 'אני הולך הביתה', words: ['אני', 'הולך', 'הביתה'], translit: 'a-NEE ho-LECH ha-BAI-ta', en: 'I am going home', emoji: '🏠' },
  { he: 'לַיְלָה טוֹב, אִמָא', plain: 'לילה טוב אמא', words: ['לילה', 'טוב', 'אמא'], translit: 'LAI-la tov, EE-ma', en: 'Good night, Mom', emoji: '🌙' },
  { he: 'קוּם! כְּבָר מְאוּחָר', plain: 'קום כבר מאוחר', words: ['קום', 'כבר', 'מאוחר'], translit: 'kum! kvar me-u-CHAR', en: 'Get up! It is already late', emoji: '⏰' },
];
const SENTENCES_TOWN = [
  { he: 'אֵיפֹה תַּחֲנַת הָאוֹטוֹבּוּס?', plain: 'איפה תחנת האוטובוס', words: ['איפה', 'תחנת', 'האוטובוס'], translit: 'EY-fo ta-cha-NAT ha-O-to-bus?', en: 'Where is the bus station?', emoji: '🚏' },
  { he: 'אֵיפֹה הַשֵּׁירוּתִים?', plain: 'איפה השירותים', words: ['איפה', 'השירותים'], translit: 'EY-fo ha-she-ru-TIM?', en: 'Where is the bathroom?', emoji: '🚻' },
  { he: 'זֶה רָחוֹק?', plain: 'זה רחוק', words: ['זה', 'רחוק'], translit: 'ze ra-CHOK?', en: 'Is it far?', emoji: '📏' },
  { he: 'זֶה קָרוֹב מְאוֹד', plain: 'זה קרוב מאוד', words: ['זה', 'קרוב', 'מאוד'], translit: 'ze ka-ROV me-OD', en: 'It is very close', emoji: '👌' },
  { he: 'סַע יָשָׁר', plain: 'סע ישר', words: ['סע', 'ישר'], translit: 'sa ya-SHAR', en: 'Drive straight', emoji: '⬆️' },
  { he: 'עֲצוֹר כָּאן, בְּבַקָּשָׁה', plain: 'עצור כאן בבקשה', words: ['עצור', 'כאן', 'בבקשה'], translit: 'a-TSOR kan, be-va-ka-SHA', en: 'Stop here, please', emoji: '🛑' },
  { he: 'הָלַכְתִּי לְאִיבּוּד', plain: 'הלכתי לאיבוד', words: ['הלכתי', 'לאיבוד'], translit: 'ha-LACH-tee le-ee-BUD', en: 'I am lost', emoji: '🧭' },
  { he: 'מָתַי מַגִּיעַ הָאוֹטוֹבּוּס?', plain: 'מתי מגיע האוטובוס', words: ['מתי', 'מגיע', 'האוטובוס'], translit: 'ma-TAI ma-GI-a ha-O-to-bus?', en: 'When does the bus arrive?', emoji: '⏱️' },
  { he: 'אֲנַחְנוּ נוֹסְעִים לְתֵל אָבִיב', plain: 'אנחנו נוסעים לתל אביב', words: ['אנחנו', 'נוסעים', 'לתל', 'אביב'], translit: 'a-NACH-nu nos-IM le-tel a-VIV', en: 'We are traveling to Tel Aviv', emoji: '🚗' },
  { he: 'הִגַּעְנוּ הַבַּיְתָה!', plain: 'הגענו הביתה', words: ['הגענו', 'הביתה'], translit: 'hi-GA-nu ha-BAI-ta!', en: 'We arrived home!', emoji: '🎉' },
];
const SENTENCES_SHOP = [
  { he: 'כַּמָּה זֶה עוֹלֶה?', plain: 'כמה זה עולה', words: ['כמה', 'זה', 'עולה'], translit: 'KA-ma ze o-LE?', en: 'How much does this cost?', emoji: '💰' },
  { he: 'יֵשׁ לְךָ מַיִם?', plain: 'יש לך מים', words: ['יש', 'לך', 'מים'], translit: 'yesh le-CHA MA-yim?', en: 'Do you have water?', emoji: '💧' },
  { he: 'זֶה יָקָר מְאוֹד', plain: 'זה יקר מאוד', words: ['זה', 'יקר', 'מאוד'], translit: 'ze ya-KAR me-OD', en: 'It is very expensive', emoji: '💸' },
  { he: 'זֶה זוֹל!', plain: 'זה זול', words: ['זה', 'זול'], translit: 'ze zol!', en: 'It is cheap!', emoji: '🤑' },
  { he: 'אֲנִי רוֹצֶה לִקְנוֹת גְּלִידָה', plain: 'אני רוצה לקנות גלידה', words: ['אני', 'רוצה', 'לקנות', 'גלידה'], translit: 'a-NEE ro-TSE lik-NOT GLEE-da', en: 'I want to buy ice cream', emoji: '🍦' },
  { he: 'תֵּן לִי אֶחָד, בְּבַקָּשָׁה', plain: 'תן לי אחד בבקשה', words: ['תן', 'לי', 'אחד', 'בבקשה'], translit: 'ten li e-CHAD, be-va-ka-SHA', en: 'Give me one, please', emoji: '☝️' },
  { he: 'כַּמָּה עוֹלֶה הַלֶּחֶם?', plain: 'כמה עולה הלחם', words: ['כמה', 'עולה', 'הלחם'], translit: 'KA-ma o-LE ha-LE-chem?', en: 'How much is the bread?', emoji: '🍞' },
  { he: 'יֵשׁ עוֹדֶף?', plain: 'יש עודף', words: ['יש', 'עודף'], translit: 'yesh O-def?', en: 'Is there change?', emoji: '🪙' },
  { he: 'אֲנִי מְשַׁלֵּם בְּכֶסֶף', plain: 'אני משלם בכסף', words: ['אני', 'משלם', 'בכסף'], translit: 'a-NEE me-sha-LEM be-KE-sef', en: 'I pay with money', emoji: '💵' },
  { he: 'תּוֹדָה רַבָּה!', plain: 'תודה רבה', words: ['תודה', 'רבה'], translit: 'to-DA ra-BA!', en: 'Thank you very much!', emoji: '🙏' },
];
const SENTENCES_HELP = [
  { he: 'אַתָּה יָכוֹל לַעֲזוֹר לִי?', plain: 'אתה יכול לעזור לי', words: ['אתה', 'יכול', 'לעזור', 'לי'], translit: 'a-TA ya-CHOL la-a-ZOR li?', en: 'Can you help me?', emoji: '🙋' },
  { he: 'אֲנִי לֹא מֵבִין', plain: 'אני לא מבין', words: ['אני', 'לא', 'מבין'], translit: 'a-NEE lo me-VIN', en: "I don't understand", emoji: '😕' },
  { he: 'תַּגִּיד עוֹד פַּעַם, בְּבַקָּשָׁה', plain: 'תגיד עוד פעם בבקשה', words: ['תגיד', 'עוד', 'פעם', 'בבקשה'], translit: 'ta-GID od PA-am, be-va-ka-SHA', en: 'Say it again, please', emoji: '🔁' },
  { he: 'אֵיךְ אוֹמְרִים אֶת זֶה בְּעִבְרִית?', plain: 'איך אומרים את זה בעברית', words: ['איך', 'אומרים', 'את', 'זה', 'בעברית'], translit: 'eych om-RIM et ze be-iv-REET?', en: 'How do you say this in Hebrew?', emoji: '🗣️' },
  { he: 'דַּבֵּר לְאַט, בְּבַקָּשָׁה', plain: 'דבר לאט בבקשה', words: ['דבר', 'לאט', 'בבקשה'], translit: 'da-BER le-AT, be-va-ka-SHA', en: 'Speak slowly, please', emoji: '🐢' },
  { he: 'מָה זֶה אוֹמֵר?', plain: 'מה זה אומר', words: ['מה', 'זה', 'אומר'], translit: 'ma ze o-MER?', en: 'What does it mean?', emoji: '🤔' },
  { he: 'אֲנִי לוֹמֵד עִבְרִית', plain: 'אני לומד עברית', words: ['אני', 'לומד', 'עברית'], translit: 'a-NEE lo-MED iv-REET', en: 'I am learning Hebrew', emoji: '📚' },
  { he: 'אַתָּה מְדַבֵּר אַנְגְּלִית?', plain: 'אתה מדבר אנגלית', words: ['אתה', 'מדבר', 'אנגלית'], translit: 'a-TA me-da-BER an-GLIT?', en: 'Do you speak English?', emoji: '🇺🇸' },
  { he: 'יֵשׁ לִי שְׁאֵלָה', plain: 'יש לי שאלה', words: ['יש', 'לי', 'שאלה'], translit: 'yesh li she-e-LA', en: 'I have a question', emoji: '❓' },
  { he: 'אֲנִי צָרִיךְ עֶזְרָה', plain: 'אני צריך עזרה', words: ['אני', 'צריך', 'עזרה'], translit: 'a-NEE tsa-RICH ez-RA', en: 'I need help', emoji: '🆘' },
];
const SENTENCES_FEEL = [
  { he: 'אֲנִי שָׂמֵחַ מְאוֹד', plain: 'אני שמח מאוד', words: ['אני', 'שמח', 'מאוד'], translit: 'a-NEE sa-ME-ach me-OD', en: 'I am very happy', emoji: '😊' },
  { he: 'אֲנִי קְצָת עָצוּב', plain: 'אני קצת עצוב', words: ['אני', 'קצת', 'עצוב'], translit: 'a-NEE ktsat a-TSUV', en: 'I am a little sad', emoji: '😢' },
  { he: 'חַם לִי!', plain: 'חם לי', words: ['חם', 'לי'], translit: 'cham li!', en: 'I am hot!', emoji: '🥵' },
  { he: 'קַר לִי!', plain: 'קר לי', words: ['קר', 'לי'], translit: 'kar li!', en: 'I am cold!', emoji: '🥶' },
  { he: 'כּוֹאֶבֶת לִי הַבֶּטֶן', plain: 'כואבת לי הבטן', words: ['כואבת', 'לי', 'הבטן'], translit: 'ko-E-vet li ha-BE-ten', en: 'My tummy hurts', emoji: '🤢' },
  { he: 'אֲנִי אוֹהֵב אוֹתְךָ', plain: 'אני אוהב אותך', words: ['אני', 'אוהב', 'אותך'], translit: 'a-NEE o-HEV ot-CHA', en: 'I love you', emoji: '❤️' },
  { he: 'זֶה מַצְחִיק!', plain: 'זה מצחיק', words: ['זה', 'מצחיק'], translit: 'ze mats-CHIK!', en: 'That is funny!', emoji: '😂' },
  { he: 'אֵיזֶה כֵּיף!', plain: 'איזה כיף', words: ['איזה', 'כיף'], translit: 'EY-ze keif!', en: 'What fun!', emoji: '🎉' },
  { he: 'אֲנִי מִתְגַּעְגֵּעַ אֵלֶיךָ', plain: 'אני מתגעגע אליך', words: ['אני', 'מתגעגע', 'אליך'], translit: 'a-NEE mit-ga-GE-a e-LE-cha', en: 'I miss you', emoji: '💌' },
  { he: 'הַכֹּל בְּסֵדֶר', plain: 'הכל בסדר', words: ['הכל', 'בסדר'], translit: 'ha-KOL be-SE-der', en: 'Everything is OK', emoji: '👌' },
];

// Level map. kind: letters | vowels | review | vocab | sentences
const LEVELS = [
  { id: 'l1',  title: 'First Letters',      sub: 'א ב ג ד ה',        emoji: '🌱', kind: 'letters',   items: LETTERS.slice(0, 5) },
  { id: 'l2',  title: 'More Letters',       sub: 'ו ז ח ט י',        emoji: '⭐', kind: 'letters',   items: LETTERS.slice(5, 10) },
  { id: 'l3',  title: 'Power Letters',      sub: 'כ ל מ נ ס',        emoji: '🚀', kind: 'letters',   items: LETTERS.slice(10, 15) },
  { id: 'l4',  title: 'Fire Letters',       sub: 'ע פ צ ק ר',        emoji: '🔥', kind: 'letters',   items: LETTERS.slice(15, 20) },
  { id: 'l5',  title: 'Finish Line Letters', sub: 'ש ת + sofit forms', emoji: '🏁', kind: 'letters',  items: [...LETTERS.slice(20, 22), ...FINALS] },
  { id: 'l6',  title: 'Alef-Bet Boss',      sub: 'All 22 letters!',   emoji: '👑', kind: 'review',    items: LETTERS },
  { id: 'l7',  title: 'Vowel Power',        sub: 'Nikud — the dots!', emoji: '🎵', kind: 'vowels',    items: VOWELS },
  { id: 'l8',  title: 'Hello Hebrew!',      sub: 'Greetings',         emoji: '👋', kind: 'vocab',     items: VOCAB.greetings },
  { id: 'l9',  title: 'My Family',          sub: 'Mishpacha',         emoji: '👨‍👩‍👧‍👦', kind: 'vocab', items: VOCAB.family },
  { id: 'l10', title: 'Count to 10',        sub: 'Numbers',           emoji: '🔢', kind: 'vocab',     items: VOCAB.numbers },
  { id: 'l11', title: 'Rainbow Words',      sub: 'Colors',            emoji: '🌈', kind: 'vocab',     items: VOCAB.colors },
  { id: 'l12', title: 'Animal Safari',      sub: 'Animals',           emoji: '🐫', kind: 'vocab',     items: VOCAB.animals },
  { id: 'l13', title: 'Yummy Hebrew',       sub: 'Food',              emoji: '🍕', kind: 'vocab',     items: VOCAB.food },
  { id: 'l19', title: 'Everyday Words',     sub: 'Daily life',        emoji: '🏠', kind: 'vocab',     items: VOCAB.everyday },
  { id: 'l20', title: 'Getting Around',     sub: 'Wheels & directions', emoji: '🚌', kind: 'vocab',   items: VOCAB.transport },
  { id: 'l21', title: 'Games & Play',       sub: 'Fun time!',         emoji: '🎲', kind: 'vocab',     items: VOCAB.games },
  { id: 'l22', title: 'Motion Words',       sub: 'Move your body!',   emoji: '🏃', kind: 'vocab',     items: VOCAB.motion },
  { id: 'l16', title: 'Science Lab',        sub: 'Science Hebrew',    emoji: '🔬', kind: 'vocab',     items: VOCAB.science },
  { id: 'l17', title: 'Space Mission',      sub: 'To the stars!',     emoji: '🚀', kind: 'vocab',     items: VOCAB.space },
  { id: 'l23', title: 'He Says, She Says',  sub: 'Boy & girl words',  emoji: '👦👧', kind: 'vocab',   items: VOCAB.gender },
  { id: 'l24', title: 'One & Many',         sub: 'Plurals: -im & -ot', emoji: '👥', kind: 'vocab',    items: VOCAB.plural },
  { id: 'l14', title: 'First Sentences',    sub: 'Say real things!',  emoji: '💬', kind: 'sentences', items: SENTENCES_1 },
  { id: 'l15', title: 'Sentence Superstar', sub: 'Questions & more',  emoji: '🏆', kind: 'sentences', items: SENTENCES_2 },
  { id: 'l18', title: 'Friendly Hebrew',    sub: 'Talk about YOU!',   emoji: '🤝', kind: 'sentences', items: SENTENCES_FRIENDLY },
  { id: 'l25', title: 'Daily Life Talk',    sub: 'Real everyday lines', emoji: '🗣️', kind: 'sentences', items: SENTENCES_LIFE },
  { id: 'l26', title: 'Getting Around Town', sub: 'Ask your way',      emoji: '🚏', kind: 'sentences', items: SENTENCES_TOWN },
  { id: 'l27', title: 'Shopping Time',      sub: 'Buy it in Hebrew',  emoji: '🛒', kind: 'sentences', items: SENTENCES_SHOP },
  { id: 'l28', title: 'Help Me Talk',       sub: 'Never get stuck',   emoji: '🙋', kind: 'sentences', items: SENTENCES_HELP },
  { id: 'l29', title: 'Feelings & Fun',     sub: 'Say how you feel',  emoji: '💬', kind: 'sentences', items: SENTENCES_FEEL },
];

// Costume shop — slots: hat | eyes | body (drawn on avatar) + hand | pet | ride | treasure (stickers)
const SHOP_SLOTS = [
  ['hat', '🎩 Hats'],
  ['eyes', '🕶️ Glasses'],
  ['body', '👕 Outfits'],
  ['hand', '🎸 Hand Stuff'],
  ['pet', '🐾 Pets'],
  ['ride', '🛴 Rides'],
  ['treasure', '💎 Treasures'],
];
const SHOP = [
  // --- hats ---
  { id: 'cap',      name: 'Cool Cap',        emoji: '🧢', cost: 25, slot: 'hat' },
  { id: 'tembel',   name: 'Tembel Hat',      emoji: '👒', cost: 30, slot: 'hat' },
  { id: 'wizard',   name: 'Wizard Hat',      emoji: '🧙', cost: 50, slot: 'hat' },
  { id: 'helmet',   name: 'Bike Helmet',     emoji: '⛑️', cost: 55, slot: 'hat' },
  { id: 'crown',    name: 'Royal Crown',     emoji: '👑', cost: 60, slot: 'hat' },
  { id: 'armyhat',  name: 'Adventure Helmet', emoji: '🪖', cost: 70, slot: 'hat' },
  { id: 'tophat',   name: 'Magician Top Hat', emoji: '🎩', cost: 85, slot: 'hat' },
  { id: 'gradcap',  name: 'Graduation Cap',  emoji: '🎓', cost: 90, slot: 'hat' },
  { id: 'cowboy',   name: 'Cowboy Hat',      emoji: '🤠', cost: 95, slot: 'hat' },
  { id: 'santa',    name: 'Santa Hat',       emoji: '🎅', cost: 110, slot: 'hat' },
  { id: 'pumpkin',  name: 'Pumpkin Head',    emoji: '🎃', cost: 150, slot: 'hat' },
  { id: 'unicornhorn', name: 'Unicorn Horn', emoji: '🦄', cost: 300, slot: 'hat' },
  { id: 'halo',     name: 'Golden Halo',     emoji: '😇', cost: 400, slot: 'hat' },
  // --- glasses ---
  { id: 'shades',   name: 'Sunglasses',      emoji: '😎', cost: 30, slot: 'eyes' },
  { id: 'starglasses', name: 'Star Glasses', emoji: '🤩', cost: 40, slot: 'eyes' },
  { id: 'nerd',     name: 'Smart Glasses',   emoji: '👓', cost: 50, slot: 'eyes' },
  { id: 'goggles',  name: 'Swim Goggles',    emoji: '🥽', cost: 55, slot: 'eyes' },
  { id: 'spy',      name: 'Spy Shades',      emoji: '🕶️', cost: 75, slot: 'eyes' },
  { id: 'disguise', name: 'Funny Disguise',  emoji: '🥸', cost: 90, slot: 'eyes' },
  { id: 'monocle',  name: 'Fancy Monocle',   emoji: '🧐', cost: 120, slot: 'eyes' },
  // --- outfits ---
  { id: 'jersey',   name: 'Soccer Jersey',   emoji: '⚽', cost: 40, slot: 'body' },
  { id: 'vest',     name: 'Builder Vest',    emoji: '🦺', cost: 45, slot: 'body' },
  { id: 'cape',     name: 'Hero Cape',       emoji: '🦸', cost: 50, slot: 'body' },
  { id: 'coat',     name: 'Winter Coat',     emoji: '🧥', cost: 60, slot: 'body' },
  { id: 'labcoat',  name: 'Scientist Lab Coat', emoji: '🥼', cost: 65, slot: 'body' },
  { id: 'astro',    name: 'Space Suit',      emoji: '👨‍🚀', cost: 70, slot: 'body' },
  { id: 'dress',    name: 'Party Dress',     emoji: '👗', cost: 80, slot: 'body' },
  { id: 'karate',   name: 'Karate Gi',       emoji: '🥋', cost: 95, slot: 'body' },
  { id: 'kimono',   name: 'Fancy Kimono',    emoji: '👘', cost: 105, slot: 'body' },
  { id: 'police',   name: 'Police Uniform',  emoji: '👮', cost: 120, slot: 'body' },
  { id: 'tux',      name: 'Fancy Tuxedo',    emoji: '🤵', cost: 150, slot: 'body' },
  { id: 'vampire',  name: 'Vampire Cloak',   emoji: '🧛', cost: 200, slot: 'body' },
  { id: 'knight',   name: 'Knight Armor',    emoji: '🤺', cost: 280, slot: 'body' },
  { id: 'mermaid',  name: 'Mermaid Tail',    emoji: '🧜', cost: 350, slot: 'body' },
  // --- hand stuff ---
  { id: 'balloon',  name: 'Balloon',         emoji: '🎈', cost: 25, slot: 'hand' },
  { id: 'yoyo',     name: 'Yo-yo',           emoji: '🪀', cost: 30, slot: 'hand' },
  { id: 'soccerball', name: 'Soccer Ball',   emoji: '⚽', cost: 35, slot: 'hand' },
  { id: 'basketball', name: 'Basketball',    emoji: '🏀', cost: 35, slot: 'hand' },
  { id: 'icecream', name: 'Ice Cream',       emoji: '🍦', cost: 40, slot: 'hand' },
  { id: 'flashlight', name: 'Flashlight',    emoji: '🔦', cost: 45, slot: 'hand' },
  { id: 'boba',     name: 'Bubble Tea',      emoji: '🧋', cost: 55, slot: 'hand' },
  { id: 'kite',     name: 'Kite',            emoji: '🪁', cost: 60, slot: 'hand' },
  { id: 'paint',    name: 'Paint Set',       emoji: '🎨', cost: 70, slot: 'hand' },
  { id: 'fishing',  name: 'Fishing Rod',     emoji: '🎣', cost: 80, slot: 'hand' },
  { id: 'controller', name: 'Game Controller', emoji: '🎮', cost: 90, slot: 'hand' },
  { id: 'micstar',  name: 'Star Microphone', emoji: '🎤', cost: 95, slot: 'hand' },
  { id: 'trumpet',  name: 'Trumpet',         emoji: '🎺', cost: 100, slot: 'hand' },
  { id: 'camera',   name: 'Camera',          emoji: '📷', cost: 110, slot: 'hand' },
  { id: 'guitar',   name: 'Rock Guitar',     emoji: '🎸', cost: 130, slot: 'hand' },
  { id: 'wand',     name: 'Magic Wand',      emoji: '🪄', cost: 180, slot: 'hand' },
  { id: 'sword',    name: 'Hero Sword',      emoji: '⚔️', cost: 220, slot: 'hand' },
  { id: 'shield',   name: 'Dragon Shield',   emoji: '🛡️', cost: 260, slot: 'hand' },
  // --- pets ---
  { id: 'goldfish', name: 'Goldfish',        emoji: '🐠', cost: 100, slot: 'pet' },
  { id: 'hamster',  name: 'Hamster',         emoji: '🐹', cost: 120, slot: 'pet' },
  { id: 'turtlepet', name: 'Pet Turtle',     emoji: '🐢', cost: 130, slot: 'pet' },
  { id: 'bunny',    name: 'Bunny',           emoji: '🐰', cost: 150, slot: 'pet' },
  { id: 'hedgehog', name: 'Hedgehog',        emoji: '🦔', cost: 160, slot: 'pet' },
  { id: 'parrot',   name: 'Parrot',          emoji: '🦜', cost: 180, slot: 'pet' },
  { id: 'puppy',    name: 'Puppy',           emoji: '🐶', cost: 200, slot: 'pet' },
  { id: 'kitten',   name: 'Kitten',          emoji: '🐱', cost: 200, slot: 'pet' },
  { id: 'owl',      name: 'Wise Owl',        emoji: '🦉', cost: 220, slot: 'pet' },
  { id: 'octopus',  name: 'Octopus',         emoji: '🐙', cost: 240, slot: 'pet' },
  { id: 'penguin',  name: 'Penguin',         emoji: '🐧', cost: 250, slot: 'pet' },
  { id: 'fox',      name: 'Fox',             emoji: '🦊', cost: 280, slot: 'pet' },
  { id: 'camelpet', name: 'Camel',           emoji: '🐫', cost: 300, slot: 'pet' },
  { id: 'koala',    name: 'Koala',           emoji: '🐨', cost: 320, slot: 'pet' },
  { id: 'llama',    name: 'Llama',           emoji: '🦙', cost: 350, slot: 'pet' },
  { id: 'pony',     name: 'Pony',            emoji: '🐴', cost: 400, slot: 'pet' },
  { id: 'babyhoopoe', name: 'Baby Hoopoe',   emoji: '🐤', cost: 450, slot: 'pet' },
  { id: 'dino',     name: 'Pet Dino',        emoji: '🦖', cost: 600, slot: 'pet' },
  { id: 'shark',    name: 'Pet Shark',       emoji: '🦈', cost: 800, slot: 'pet' },
  { id: 'dragon',   name: 'Dragon',          emoji: '🐉', cost: 1200, slot: 'pet' },
  { id: 'unicornpet', name: 'Unicorn',       emoji: '🦄', cost: 1500, slot: 'pet' },
  // --- rides ---
  { id: 'scooter',  name: 'Scooter',         emoji: '🛴', cost: 130, slot: 'ride' },
  { id: 'skates',   name: 'Roller Skates',   emoji: '🛼', cost: 140, slot: 'ride' },
  { id: 'skateboard', name: 'Skateboard',    emoji: '🛹', cost: 150, slot: 'ride' },
  { id: 'sled',     name: 'Snow Sled',       emoji: '🛷', cost: 180, slot: 'ride' },
  { id: 'canoe',    name: 'Canoe',           emoji: '🛶', cost: 200, slot: 'ride' },
  { id: 'bike',     name: 'Bicycle',         emoji: '🚲', cost: 250, slot: 'ride' },
  { id: 'carousel', name: 'Carousel Horse',  emoji: '🎠', cost: 350, slot: 'ride' },
  { id: 'familycar', name: 'Family Car',     emoji: '🚗', cost: 400, slot: 'ride' },
  { id: 'sailboat', name: 'Sailboat',        emoji: '⛵', cost: 450, slot: 'ride' },
  { id: 'partybus', name: 'Party Bus',       emoji: '🚌', cost: 500, slot: 'ride' },
  { id: 'motorbike', name: 'Motorbike',      emoji: '🏍️', cost: 550, slot: 'ride' },
  { id: 'trainride', name: 'Train',          emoji: '🚂', cost: 600, slot: 'ride' },
  { id: 'racecar',  name: 'Race Car',        emoji: '🏎️', cost: 750, slot: 'ride' },
  { id: 'helicopter', name: 'Helicopter',    emoji: '🚁', cost: 900, slot: 'ride' },
  { id: 'jet',      name: 'Jet Plane',       emoji: '✈️', cost: 1100, slot: 'ride' },
  { id: 'rocket',   name: 'Rocket Ship',     emoji: '🚀', cost: 1500, slot: 'ride' },
  { id: 'ufo',      name: 'UFO',             emoji: '🛸', cost: 2000, slot: 'ride' },
  // --- treasures ---
  { id: 'goldstar', name: 'Gold Star',       emoji: '⭐', cost: 150, slot: 'treasure' },
  { id: 'badge',    name: 'Champion Badge',  emoji: '🏅', cost: 180, slot: 'treasure' },
  { id: 'goldmedal', name: 'Gold Medal',     emoji: '🥇', cost: 200, slot: 'treasure' },
  { id: 'charm',    name: 'Lucky Charm',     emoji: '🧿', cost: 220, slot: 'treasure' },
  { id: 'heromedal', name: 'Hero Medal',     emoji: '🎖️', cost: 250, slot: 'treasure' },
  { id: 'gift',     name: 'Mystery Gift',    emoji: '🎁', cost: 275, slot: 'treasure' },
  { id: 'trophy',   name: 'Gold Trophy',     emoji: '🏆', cost: 300, slot: 'treasure' },
  { id: 'superstar', name: 'Super Star',     emoji: '🌟', cost: 350, slot: 'treasure' },
  { id: 'disco',    name: 'Disco Ball',      emoji: '🪩', cost: 380, slot: 'treasure' },
  { id: 'moneybag', name: 'Money Bag',       emoji: '💰', cost: 400, slot: 'treasure' },
  { id: 'crystal',  name: 'Crystal Ball',    emoji: '🔮', cost: 450, slot: 'treasure' },
  { id: 'ring',     name: 'Diamond Ring',    emoji: '💍', cost: 500, slot: 'treasure' },
  { id: 'pirate',   name: 'Pirate Flag',     emoji: '🏴‍☠️', cost: 550, slot: 'treasure' },
  { id: 'statue',   name: 'Mystery Statue',  emoji: '🗿', cost: 650, slot: 'treasure' },
  { id: 'gem',      name: 'Diamond',         emoji: '💎', cost: 800, slot: 'treasure' },
  { id: 'trident',  name: 'Golden Trident',  emoji: '🔱', cost: 900, slot: 'treasure' },
  { id: 'bluegem',  name: 'Rare Blue Diamond', emoji: '💠', cost: 1500, slot: 'treasure' },
  { id: 'megagem',  name: 'Legendary Mega Diamond', emoji: '🔷', cost: 2500, slot: 'treasure' },
];

const RANKS = [
  { xp: 0,   name: 'Newbie',      emoji: '🐣' },
  { xp: 100, name: 'Explorer',    emoji: '🧭' },
  { xp: 250, name: 'Rising Star', emoji: '🌟' },
  { xp: 500, name: 'Champion',    emoji: '🏅' },
  { xp: 900, name: 'Hebrew Hero', emoji: '🦸' },
];

const HOME_TIPS = [
  'Hebrew is read from RIGHT to LEFT ← that way!',
  'Hebrew has 22 letters — and 5 of them change shape at the end of a word!',
  '"Shalom" means hello, goodbye AND peace. Three words in one!',
  'Hebrew is over 3,000 years old — you are learning an ancient superpower!',
  'The word "abba" (dad) is one of the oldest words still used today!',
  'Tap the 🔊 button any time to hear a word again.',
  'Say the words OUT LOUD — your mouth remembers better than your eyes!',
  'Practice a little every day — streaks beat marathons!',
];
